package redJpa.entities;

// default package
// Generated 27/04/2020 11:14:40 PM by Hibernate Tools 5.4.14.Final

/**
 * Usuario generated by hbm2java
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated 27/04/2020 08:42:06 PM by Hibernate Tools 5.4.14.Final

/**
 * Usuario generated by hbm2java
 */

@Entity
@Table(name="usuario")
public class Usuario implements java.io.Serializable {
    @Id
	private String usuario;
    @Column
	private String clave;
    @Column
	private String nombre;
    @Column
	private String direccion;
    @Column
	private String telefono;
    @Column
	private String correo;


	public Usuario() {
	}

	public Usuario(String usuario, String clave, String nombre, String direccion, String telefono, String correo) {
		this.usuario = usuario;
		this.clave = clave;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

}
